[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "ModImporter"
versionNumber = "1.6.0"
description = "Defines and executes a format for modifying the data files of SuperGiant Games' games."
websiteUrl = "https://github.com/SGG-Modding/ModImporter"
containsNsfwContent = false

[package.dependencies]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "tools", ]
